/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CommanderRouteImport } from './routes/commander'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CuisineRouteImport } from './routes/cuisine'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as LaCarteRouteImport } from './routes/la-carte'
import { Route as MerciRouteImport } from './routes/merci'
import { Route as NotreHistoireRouteImport } from './routes/notre-histoire'
import { Route as SuiviIdRouteImport } from './routes/suivi.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CommanderRoute = CommanderRouteImport.update({
  id: '/commander',
  path: '/commander',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CuisineRoute = CuisineRouteImport.update({
  id: '/cuisine',
  path: '/cuisine',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const LaCarteRoute = LaCarteRouteImport.update({
  id: '/la-carte',
  path: '/la-carte',
  getParentRoute: () => rootRouteImport,
} as any)
const MerciRoute = MerciRouteImport.update({
  id: '/merci',
  path: '/merci',
  getParentRoute: () => rootRouteImport,
} as any)
const NotreHistoireRoute = NotreHistoireRouteImport.update({
  id: '/notre-histoire',
  path: '/notre-histoire',
  getParentRoute: () => rootRouteImport,
} as any)
const SuiviIdRoute = SuiviIdRouteImport.update({
  id: '/suivi/$id',
  path: '/suivi/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/commander': typeof CommanderRoute
  '/contact': typeof ContactRoute
  '/cuisine': typeof CuisineRoute
  '/galerie': typeof GalerieRoute
  '/la-carte': typeof LaCarteRoute
  '/merci': typeof MerciRoute
  '/notre-histoire': typeof NotreHistoireRoute
  '/suivi/$id': typeof SuiviIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/commander': typeof CommanderRoute
  '/contact': typeof ContactRoute
  '/cuisine': typeof CuisineRoute
  '/galerie': typeof GalerieRoute
  '/la-carte': typeof LaCarteRoute
  '/merci': typeof MerciRoute
  '/notre-histoire': typeof NotreHistoireRoute
  '/suivi/$id': typeof SuiviIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/checkout': typeof CheckoutRoute
  '/commander': typeof CommanderRoute
  '/contact': typeof ContactRoute
  '/cuisine': typeof CuisineRoute
  '/galerie': typeof GalerieRoute
  '/la-carte': typeof LaCarteRoute
  '/merci': typeof MerciRoute
  '/notre-histoire': typeof NotreHistoireRoute
  '/suivi/$id': typeof SuiviIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/commander'
    | '/contact'
    | '/cuisine'
    | '/galerie'
    | '/la-carte'
    | '/merci'
    | '/notre-histoire'
    | '/suivi/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/checkout'
    | '/commander'
    | '/contact'
    | '/cuisine'
    | '/galerie'
    | '/la-carte'
    | '/merci'
    | '/notre-histoire'
    | '/suivi/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/commander'
    | '/contact'
    | '/cuisine'
    | '/galerie'
    | '/la-carte'
    | '/merci'
    | '/notre-histoire'
    | '/suivi/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CheckoutRoute: typeof CheckoutRoute
  CommanderRoute: typeof CommanderRoute
  ContactRoute: typeof ContactRoute
  CuisineRoute: typeof CuisineRoute
  GalerieRoute: typeof GalerieRoute
  LaCarteRoute: typeof LaCarteRoute
  MerciRoute: typeof MerciRoute
  NotreHistoireRoute: typeof NotreHistoireRoute
  SuiviIdRoute: typeof SuiviIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commander': {
      id: '/commander'
      path: '/commander'
      fullPath: '/commander'
      preLoaderRoute: typeof CommanderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuisine': {
      id: '/cuisine'
      path: '/cuisine'
      fullPath: '/cuisine'
      preLoaderRoute: typeof CuisineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gestao': {
      id: '/gestao'
      path: '/gestao'
      fullPath: '/gestao'
      preLoaderRoute: typeof GestaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/la-carte': {
      id: '/la-carte'
      path: '/la-carte'
      fullPath: '/la-carte'
      preLoaderRoute: typeof LaCarteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merci': {
      id: '/merci'
      path: '/merci'
      fullPath: '/merci'
      preLoaderRoute: typeof MerciRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notre-histoire': {
      id: '/notre-histoire'
      path: '/notre-histoire'
      fullPath: '/notre-histoire'
      preLoaderRoute: typeof NotreHistoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suivi/$id': {
      id: '/suivi/$id'
      path: '/suivi/$id'
      fullPath: '/suivi/$id'
      preLoaderRoute: typeof SuiviIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CheckoutRoute: CheckoutRoute,
  CommanderRoute: CommanderRoute,
  ContactRoute: ContactRoute,
  CuisineRoute: CuisineRoute,
  GalerieRoute: GalerieRoute,
  LaCarteRoute: LaCarteRoute,
  MerciRoute: MerciRoute,
  NotreHistoireRoute: NotreHistoireRoute,
  SuiviIdRoute: SuiviIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
